### ISSUE TITLE
input size of irtr_rank_output

### ISSUE THREAD

**Issue by jim4399266** [zdou0830/METER#15]
Honourable authors:
Thanks for your excellent jobs! I have 2 questions when I did itrt task. 

1. First, I found the output size of **infer["cls_feats"]** in [**compute_irtr**](https://github.com/zdou0830/METER/blob/main/meter/modules/objectives.py) function (line 266) is twice of hidden_size, but the in_features of **pl_module.rank_output** function is same as hidden_size, how to understand it? 
2. Second,  why add **token_type_embedding** for text_embeds and image_embeds in [infer](https://github.com/zdou0830/METER/blob/main/meter/modules/meter_module.py) function(line 203)?

**Comment by zdou0830** [comment]
Hi,

1. Sorry for the confusion. The in features of pl_module.rank_output is actually 2*hidden_size (because of these two lines https://github.com/zdou0830/METER/blob/main/meter/modules/meter_module.py#L153-L154).
2. I followed [ViLT](https://github.com/dandelin/ViLT) to add the token_type_embeddings. I think it could be removed but I didn't do the ablation.

**Comment by jim4399266** [comment]
Thanks a lot for reply!
