### ISSUE TITLE
training steps

### ISSUE THREAD

**Issue by mactavish91** [zdou0830/METER#36]
Hello, the author. When I read the paper, I found that when the encoder is clip32, 50000 steps were trained, and when the encoder is clip16, 100000 steps were trained. Is it because the convergence time of clip32 is shorter than that of clip16, or just to reduce the training time?

**Comment by zdou0830** [comment]
Hi, we actually also train clip32 for 100k steps to get the results in the main paper. we train clip32 for 50k steps for the ablations on the pretraining datasets in the appendix because there are fewer data in that setting. 

In practice, we found that training models for 50k steps can achieve pretty decent performance.
